### ISSUE TITLE
Node Abstraction

### ISSUE THREAD

**Issue by brewkode** [ashwanthkumar/suuchi#13]
Following needs to be done to get a working cluster with membership in place.
- [x] Build a Node abstraction
- [x] Compose <s>membership</s>, partitioner & services as part of it.
- [x] When the node is started, it should expose a listen port & should be able to handle GET / PUT requests.

**Comment by ashwanthkumar** [comment]
Picking up the first part on Node Abstraction.

**Comment by ashwanthkumar** [comment]
Closing this since we've build everything except Membership. Tracking it as part of #20
