### ISSUE TITLE
HTTP Service support for each node to talk to each other

### ISSUE THREAD

**Issue by brewkode** [ashwanthkumar/suuchi#4]
- [x] gRPC <-> HTTP
- [x] GET - input key, return back the data as "bytes"
- [x] PUT - input key, data bytes
- [x] HEALTH - Report health of the node
- [x] <s>SHARD_INFO - Should report current shards that this node manages</s>

**Comment by ashwanthkumar** [comment]
Picking this up!

**Comment by ashwanthkumar** [comment]
Tracking the SHARD_INFO as part of #20 - since we might need that info only as part of rebalancing. Closing this task.
